### ISSUE TITLE
document ignore/exclude option

### ISSUE THREAD

**Issue by ORESoftware** [rogierschouten/gulp-typedoc#18]
Hey there, in the docs, it doesn't use an ignore/exclude option.

Since ignoring node_modules is such a common task, it would be really convenient to document this.

This is what is in the readme:

```js
var typedoc = require("gulp-typedoc");

gulp.task("typedoc", function() {
	return gulp
		.src(["data/*.ts"])
		.pipe(typedoc({
			// TypeScript options (see typescript docs)
			module: "commonjs",
			target: "es5",
			includeDeclarations: true,

			// Output options (see typedoc docs)
			out: "./out",
			json: "output/to/file.json",

			// TypeDoc options (see typedoc docs)
			name: "my-project",
			theme: "/path/to/my/theme",
			plugins: ["my", "plugins"],
			ignoreCompilerErrors: false,
			version: true,
		}));
});

```
I tried this and it seems to work (but I am not sure whether it's ignore or exclude that's actually doing the work:

```js
gulp.task('typedoc', function() {
  return gulp
  .src([path.resolve(`${sumanRoot}/**/*.ts`)])
  .pipe(typedoc({
    module: 'commonjs',
    target: 'es5',
    ignore: '**/node_modules/**',           // <<<<<<<<<<<<<<<<
    exclude: '**/node_modules/**',        // <<<<<<<<<<<<<<< 
    out: 'typedocs/',
    ignoreCompilerErrors: true,
    version: true,
    name: 'The SumanJS Documentation'
  }));
});
```

**Comment by rogierschouten** [comment]
Hi @ORESoftware, thank you for creating this issue here.  Whether ignore or exclude does the job, is up to typedoc. According to https://github.com/TypeStrong/typedoc  it should be 'exclude'.  The only thing that gulp-typedoc does is to pass on whatever arguments you happen to give.   I'm a bit careful with what I show in the readme because different versions of typedoc have different sets of possible arguments, hence what you tried now may not work with every version of typedoc.   Really people should be looking at http://typedoc.org/ for possible arguments.

If you feel you can make the readme more clear in this respect, I'm more than happy to merge a PR.

**Comment by ORESoftware** [comment]
I think it would be great if the README has the exclude option demonstrated. The reason why it's ambiguous, even for someone with a few years of Node.js experience, is that I don't know if the options used by this lib are Gulp flavored or Typedoc flavored. In fact, initially I expected the options to be Gulp flavored, that's why I was unsure.

I think for README files, 90% of the time it's best to this:

1. put a simple case with the most commonly used options.

2. put in a exhaustive case with all of the current options.

So maybe put an example with all options, including exclude.

**Comment by rogierschouten** [comment]
I'm closing this because you didn't submit a PR. Please feel free to still do so though.
