### ISSUE TITLE
Cannot give --includeDeclarations option

### ISSUE THREAD

**Issue by jasongrout** [rogierschouten/gulp-typedoc#2]
Is there a way to specify an option that doesn't take an argument?  It seems that the code at https://github.com/rogierschouten/gulp-typedoc/blob/master/index.js#L19 always assumes there will be an argument to any option.  Perhaps that line could be modified to only push the value if the value is non-null.

**Comment by rogierschouten** [comment]
Good point, thank you for reporting. I've created a version 1.1.0 where you can give boolean options, like so:

```javascript
var typedoc = require("gulp-typedoc");

gulp.task("typedoc", function() {
	return gulp
		.src(["data/*.ts"])
		.pipe(typedoc({ 
			module: "commonjs", 
			out: "./out", 
			name: "my-project", 
			target: "es5",
			includeDeclarations: true
		}))
	;
});
```

Setting the includeDeclarations to false would exclude it entirely, setting it to true results in just "--includeDeclarations".  I think this is a more intuitive interface than setting it to null, would you agree?

Hope this solves your problem, otherwise let me know.

**Comment by jasongrout** [comment]
It works great!  Thanks!
